name = "miruka-gitcore"
main = "./build/index.js"
workers_dev = true
compatibility_date = "2022-11-30"

kv_namespaces = [{ binding = "DB", id = "293ac4c6310245ee8b87c7a070ae24b2" }]

[build]
command = "yarn build"

[vars]
# Sensitive data should be stored in the worker itself as an encrypted value... in other terms: NOT IN THIS FILE!
# Method 1 is to use the `wrangler` command: `wrangler secret put <key>` where key is the environment variable name
# Method 2 is to put them in through the workers dashboard
#
# Sensitive environment variables:
# - GITHUB_WEBHOOK_SECRET - your secret for webhooks
# - DISCORD_WEBHOOK       - your discord webhook link (needs to be in a forum channel!)
# All sensitive variables get a default value of "" just so the worker doesn't crash

IGNORED_USERS = "renovate[bot],github-actions[bot],cloudflare-pages[bot]"
FALLBACK_URL = "https://github.com/Mirukali/miruka-gitcord" # Fallback URL for when a user types the worker address
